name: Build resume from LaTeX sources

on:
  push:
    branches: [ "main", "feature/compile-with-github-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
      
    - name: pdflatex resume-en
      uses: dante-ev/latex-action@latest
      with:
        root_file: resume-en.tex
        compiler: pdflatex
        args: -interaction=nonstopmode -shell-escape
    - name: pdflatex resume-ru
      uses: dante-ev/latex-action@latest
      with:
        root_file: resume-ru.tex
        compiler: pdflatex
        args: -interaction=nonstopmode -shell-escape

    - name: Commit and push compiled PDFs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *.pdf
        git commit -m 'Update compiled PDFs'
        git push